import random

class Coordinates:
  def __init__(self, latitude, longitude):
    self.latitude = latitude
    self.longitude = longitude

class Facility:
    def __init__(self, data):
        self.objectid = data.get("OBJECTID")
        self.globalid = data.get("globalid")
        self.nhfr_uid = data.get("nhfr_uid")
        self.nhfr_facility_code = data.get("nhfr_facility_code")
        self.country = data.get("country")
        self.iso = data.get("iso")
        self.state = data.get("state")
        self.lga = data.get("lga")
        self.lga_name_disagreement = data.get("lga_name_disagreement")
        self.ward = data.get("ward")
        self.ward_name_disagreement = data.get("ward_name_disagreement")
        self.facility_name = data.get("facility_name")
        self.facility_name_source = data.get("facility_name_source")
        self.ownership = data.get("ownership")
        self.ownership_type = data.get("ownership_type")
        self.facility_level = data.get("facility_level")
        self.facility_level_option = data.get("facility_level_option")
        self.latitude = data.get("latitude")
        self.longitude = data.get("longitude")
        self.geocoordinates_source = data.get("geocoordinates_source")
        self.last_updated = data.get("last_updated")
        
    def coordinates(self):
      return Coordinates(self.latitude, self.longitude)
      
    def get_nudged_coordinates(self):
        nudged_lat = self.latitude + random.gauss(0.00001, 0.001)
        nudged_lng = self.longitude + random.gauss(0.00001, 0.001)
        return Coordinates(nudged_lat, nudged_lng)
      
    def __repr__(self):
       return f"Facility(facility_name={self.facility_name}, state={self.state}, lga={self.lga})"
        
def random_facility(index=None):
  '''
  Get a facility from the list of facilities. If index is not provided, a random facility is returned.
  '''
  if index is None:
      index = random.randint(0, len(facilities) - 1)
  return Facility(facilities[index])


facilities = [
  {
    "OBJECTID": 8898,
    "globalid": "dd406d00-6708-4c6c-9b81-c6b903e405b4",
    "nhfr_uid": 74904051,
    "nhfr_facility_code": "33/17/1/2/1/0001",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Rijiya A",
    "ward_name_disagreement": 1,
    "facility_name": "Sokoto Hospital Specialist",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Secondary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0622968415,
    "longitude": 5.25763348855,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 10428,
    "globalid": "3cc41bcb-9030-4284-8715-7b072f55097f",
    "nhfr_uid": 86763766,
    "nhfr_facility_code": "33/17/1/1/1/0018",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Zamfara B",
    "ward_name_disagreement": 0,
    "facility_name": "Yar Akiya Basic Health Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.054354,
    "longitude": 5.236272,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 10446,
    "globalid": "eea151d5-7174-48a6-bc1d-79f1f1fe6f7b",
    "nhfr_uid": 59841834,
    "nhfr_facility_code": "33/17/1/1/1/0008",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi C",
    "ward_name_disagreement": 0,
    "facility_name": "Mabera Basic Health Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Clinic",
    "latitude": 13.0306799999,
    "longitude": 5.24991500027,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 10451,
    "globalid": "dbe85a75-6c33-4cd1-9b48-1ab72f627525",
    "nhfr_uid": 27547933,
    "nhfr_facility_code": "33/16/1/1/1/0002",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Magajin Gari B",
    "ward_name_disagreement": 0,
    "facility_name": "Assada Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Clinic",
    "latitude": 13.0663010001,
    "longitude": 5.23881299973,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 10456,
    "globalid": "cbfdbee7-96cc-4e0e-b0e8-590727098f57",
    "nhfr_uid": 41730246,
    "nhfr_facility_code": "33/16/1/1/1/0008",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Waziri C",
    "ward_name_disagreement": 0,
    "facility_name": "Kofar Rini Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0670389996,
    "longitude": 5.25659199981,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 10458,
    "globalid": "6be05932-7a46-4f0b-b8a8-0fadbb491da4",
    "nhfr_uid": 41913324,
    "nhfr_facility_code": "33/17/1/1/1/0003",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi A",
    "ward_name_disagreement": 0,
    "facility_name": "Gagi Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0461700005,
    "longitude": 5.2786569998,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11002,
    "globalid": "e522e6a9-636f-446d-ac60-25c3e4c3124b",
    "nhfr_uid": 23218916,
    "nhfr_facility_code": "33/16/1/2/1/0001",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Adar Gandu",
    "ward_name_disagreement": 0,
    "facility_name": "Noma Hospital",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Secondary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0670169996,
    "longitude": 5.21458400027,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11008,
    "globalid": "a6e2e25c-6394-487e-b8b3-3f571aa79924",
    "nhfr_uid": 83033095,
    "nhfr_facility_code": "33/16/1/1/1/0003",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Adar Gandu",
    "ward_name_disagreement": 0,
    "facility_name": "Market Health Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.059652,
    "longitude": 5.223727,
    "geocoordinates_source": "NHFR_2024",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11019,
    "globalid": "d8ad05d8-1c0c-4ad8-a138-42291cb2f007",
    "nhfr_uid": 14464250,
    "nhfr_facility_code": "33/16/1/1/1/0009",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Musulmi B",
    "ward_name_disagreement": 0,
    "facility_name": "Rinin Tawaye Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0641189997,
    "longitude": 5.24265000034,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11021,
    "globalid": "2cb44878-58d9-4601-8031-537134d6c1ef",
    "nhfr_uid": 76103587,
    "nhfr_facility_code": "33/17/1/1/1/0014",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Tudun Wada B (Sokoto South)",
    "ward_name_disagreement": 0,
    "facility_name": "Police Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Unknown",
    "latitude": 13.0338340001,
    "longitude": 5.24643699991,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11025,
    "globalid": "61fa259d-7039-48ff-a9be-3c69549507b0",
    "nhfr_uid": 52774310,
    "nhfr_facility_code": "33/17/1/1/1/0002",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Tudun Wada A (Sokoto South)",
    "ward_name_disagreement": 1,
    "facility_name": "Dallatu Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0546490002,
    "longitude": 5.25626299959,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11028,
    "globalid": "820b8b6d-81f6-4cad-9bbc-e76888cf98e7",
    "nhfr_uid": 19141415,
    "nhfr_facility_code": "33/17/1/1/1/0011",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi A",
    "ward_name_disagreement": 0,
    "facility_name": "Mana Tudu Health Post",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.021969,
    "longitude": 5.27106599964,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11031,
    "globalid": "a5dc6e7a-6056-422a-b73d-04e74d9b53ec",
    "nhfr_uid": 62089283,
    "nhfr_facility_code": "33/17/1/1/1/0010",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi A",
    "ward_name_disagreement": 0,
    "facility_name": "Mana Babba Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0287329996,
    "longitude": 5.27573299981,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11035,
    "globalid": "f0d0bcfb-1b10-45ff-b392-6c61527bfa7f",
    "nhfr_uid": 82886614,
    "nhfr_facility_code": "33/17/1/1/1/0005",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi A",
    "ward_name_disagreement": 0,
    "facility_name": "Gidan Masau Health Post",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0328520004,
    "longitude": 5.28280599962,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11198,
    "globalid": "74e163b7-ea5b-44a2-b9e5-c66ee2f3c6dc",
    "nhfr_uid": 16029793,
    "nhfr_facility_code": "33/16/1/1/1/0013",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Adar Gidan Egwai",
    "ward_name_disagreement": 0,
    "facility_name": "Tudun Faila Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.067527,
    "longitude": 5.1984460003,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11200,
    "globalid": "1683c622-6729-4c5a-b446-9726af4af867",
    "nhfr_uid": 25742670,
    "nhfr_facility_code": "33/17/1/2/2/0008",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Adar A",
    "ward_name_disagreement": 0,
    "facility_name": "Mariam Abacha Women and Children",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Secondary",
    "facility_level_option": "General Hospital",
    "latitude": 13.0625239996,
    "longitude": 5.23233500033,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11201,
    "globalid": "58b1b0d8-b697-4d74-b1bf-d50389cb19ee",
    "nhfr_uid": 87282224,
    "nhfr_facility_code": "33/16/1/1/1/0006",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Magajin Gari A",
    "ward_name_disagreement": 0,
    "facility_name": "Helele Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Clinic",
    "latitude": 13.0729189996,
    "longitude": 5.23978300039,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11296,
    "globalid": "aced0dc3-0a0d-48eb-a757-18f2a83f9aa5",
    "nhfr_uid": 78346664,
    "nhfr_facility_code": "33/17/1/1/1/0009",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi B",
    "ward_name_disagreement": 0,
    "facility_name": "Mabera Mujaya Health Post",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0127239997,
    "longitude": 5.25274100019,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11297,
    "globalid": "85159e82-b55d-4257-8ab5-6cc34a71b11c",
    "nhfr_uid": 59337650,
    "nhfr_facility_code": "33/17/1/1/1/0016",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Tudun Wada A (Sokoto South)",
    "ward_name_disagreement": 0,
    "facility_name": "Tudun Wada Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0620700003,
    "longitude": 5.25822699992,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11298,
    "globalid": "c314fca0-b4c3-4f10-9266-e91b9b40d825",
    "nhfr_uid": 76748634,
    "nhfr_facility_code": "33/17/1/1/1/0004",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi C",
    "ward_name_disagreement": 0,
    "facility_name": "Gidan Dahala Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0258769997,
    "longitude": 5.26656099958,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11368,
    "globalid": "b3b30f36-0fe2-4c9d-87f4-48b815c7a777",
    "nhfr_uid": 61117574,
    "nhfr_facility_code": "33/16/1/1/1/0010",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Waziri A",
    "ward_name_disagreement": 0,
    "facility_name": "Rumbukawa Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0786389995,
    "longitude": 5.24695500026,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11371,
    "globalid": "534a1092-5024-4d10-a9b5-43e78103f24c",
    "nhfr_uid": 43600064,
    "nhfr_facility_code": "33/17/1/1/1/0012",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Tudun Wada A (Sokoto South)",
    "ward_name_disagreement": 1,
    "facility_name": "Minanata Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0464559997,
    "longitude": 5.25656099979,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 11548,
    "globalid": "405a093d-6ba2-4c26-98b7-5e198b4473c5",
    "nhfr_uid": 34557382,
    "nhfr_facility_code": "33/16/1/1/1/0005",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 1,
    "ward": "Sarkin Adar Gandu",
    "ward_name_disagreement": 1,
    "facility_name": "Gidan Dare Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0536129995,
    "longitude": 5.20922199962,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 12179,
    "globalid": "76bfe50d-a296-4f37-be77-03799fd221b6",
    "nhfr_uid": 24024097,
    "nhfr_facility_code": "33/17/1/1/1/0017",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Zamfara A",
    "ward_name_disagreement": 0,
    "facility_name": "Turaki Basic Health Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.05133,
    "longitude": 5.23800700018,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 12216,
    "globalid": "45abced6-aa5e-43c3-a2ba-1eb07faaf9e7",
    "nhfr_uid": 79541084,
    "nhfr_facility_code": "33/17/1/1/1/0001",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 1,
    "ward": "Sarkin Adar A",
    "ward_name_disagreement": 0,
    "facility_name": "Aliyu Jodi Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0582459997,
    "longitude": 5.22879799992,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 12443,
    "globalid": "e6b22fad-0179-48ec-bb88-ec4962e19767",
    "nhfr_uid": 76511786,
    "nhfr_facility_code": "33/17/1/1/1/0015",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Rijiya B",
    "ward_name_disagreement": 0,
    "facility_name": "Sheikh Gumi Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0339527837,
    "longitude": 5.23947132993,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 13295,
    "globalid": "363103a7-7d1e-4ff4-b357-f68d52bfa289",
    "nhfr_uid": 21542208,
    "nhfr_facility_code": "33/17/1/1/2/0001",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Tudun Wada B (Sokoto South)",
    "ward_name_disagreement": 0,
    "facility_name": "Planned Parenthood Federation Of Nigeria Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "Federal Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0445810004,
    "longitude": 5.25090399994,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 19045,
    "globalid": "6914120d-f5f9-4413-a3f5-16fb5919cf7a",
    "nhfr_uid": 77764789,
    "nhfr_facility_code": "33/16/1/1/1/0001",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Magajin Rafi A",
    "ward_name_disagreement": 0,
    "facility_name": "Alkammawa Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0620322105,
    "longitude": 5.24951413133,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 22863,
    "globalid": "1a0d690e-f538-415a-9129-0c89bef54a0f",
    "nhfr_uid": 83822634,
    "nhfr_facility_code": "33/16/1/1/1/0007",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Adar Gandu",
    "ward_name_disagreement": 0,
    "facility_name": "Kofar Kade Primary Health Center",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.065354,
    "longitude": 5.223601,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 28728,
    "globalid": "6d15bc6b-54cf-4527-afe8-5c1eb748b272",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Zamfara B",
    "ward_name_disagreement": 0,
    "facility_name": "Mankeri Health Post",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0456,
    "longitude": 5.23279,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 34819,
    "globalid": "51d5356e-a1e0-49bd-9748-5061f9bacae3",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Adar Gandu",
    "ward_name_disagreement": 0,
    "facility_name": "Sokoto Central Market Clinic",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0600019999,
    "longitude": 5.21806199963,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 34821,
    "globalid": "38f8e054-7eba-4c2b-9325-a517e8aa7a81",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Adar Gandu",
    "ward_name_disagreement": 0,
    "facility_name": "Kafar Kade Clinic",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0663860002,
    "longitude": 5.22522100049,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 34823,
    "globalid": "d92ca341-3ff2-41b5-9e25-288cfd26f2f3",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Adar A",
    "ward_name_disagreement": 0,
    "facility_name": "Yan Harawa Clinic",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0637410004,
    "longitude": 5.23068500021,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 34827,
    "globalid": "aa0f4f86-f918-480f-9edf-761247dcb3cf",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Waziri A",
    "ward_name_disagreement": 0,
    "facility_name": "Adamawa Gidan Bello Sokoto Clinic",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0724990004,
    "longitude": 5.24697300027,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 34828,
    "globalid": "3f56dd5f-07fe-4eb8-9964-25707ba5c133",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Tudun Wada A (Sokoto South)",
    "ward_name_disagreement": 0,
    "facility_name": "Marina Clinic",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0545420001,
    "longitude": 5.24753299965,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 34829,
    "globalid": "18c3e095-b941-4428-b7e2-3d109ee9720e",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi C",
    "ward_name_disagreement": 0,
    "facility_name": "Wali Bako Clinic",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0379979999,
    "longitude": 5.25188899961,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 35384,
    "globalid": "0900465d-7c55-40f7-8594-a12657b4d243",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi C",
    "ward_name_disagreement": 0,
    "facility_name": "Mana Health Post",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0280670002,
    "longitude": 5.26321500031,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 35410,
    "globalid": "89a0454a-ac4b-41f9-be0f-69f71b037aae",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi C",
    "ward_name_disagreement": 0,
    "facility_name": "Murtala Hospital",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0430410003,
    "longitude": 5.26051900048,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 35543,
    "globalid": "44b00c4f-5852-4e9d-bd6a-9b36084170d6",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Rijiya A",
    "ward_name_disagreement": 0,
    "facility_name": "Shiyar Marina Specialist Hospital",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Tertiary",
    "facility_level_option": "General Hospital",
    "latitude": 13.0537079996,
    "longitude": 5.24597199959,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 35579,
    "globalid": "686f82e9-ad05-41d3-9db9-39728a1f62d4",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Magajin Gari B",
    "ward_name_disagreement": 0,
    "facility_name": "Badano Health Post",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.0757051695,
    "longitude": 5.21778948606,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 36754,
    "globalid": "c50ec95b-cf46-499a-bb0e-9332b62cbc3e",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Magajin Gari B",
    "ward_name_disagreement": 0,
    "facility_name": "Abubakar Gadanga Health Center",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0688803,
    "longitude": 5.2284619,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 36759,
    "globalid": "d9713b79-d87b-4664-9b72-683b3cdf1407",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Zamfara B",
    "ward_name_disagreement": 0,
    "facility_name": "Turaki Primary Health Center",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0490591754,
    "longitude": 5.235169373,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 38276,
    "globalid": "bc4e26df-1913-4e67-b33d-fbdf0e3a86e9",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Gagi C",
    "ward_name_disagreement": 0,
    "facility_name": "Anas Medical",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0434969996,
    "longitude": 5.25386799996,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 39797,
    "globalid": "0a40d01e-1d65-4480-966d-3f2fe04d301f",
    "nhfr_uid": None,
    "nhfr_facility_code": "",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto South",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Zamfara B",
    "ward_name_disagreement": 0,
    "facility_name": "Karfen Sarki Primary Health Center",
    "facility_name_source": "GRID3_EHEALTH",
    "ownership": "Public",
    "ownership_type": "Unknown",
    "facility_level": "Primary",
    "facility_level_option": "Primary Health Center",
    "latitude": 13.0452886,
    "longitude": 5.2337604,
    "geocoordinates_source": "GRID3_EHEALTH",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 46745,
    "globalid": "4eb5b0d0-c8cf-4f7c-a652-f45a5df77862",
    "nhfr_uid": 31058021,
    "nhfr_facility_code": "33/16/1/1/1/0014",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Musulmi A",
    "ward_name_disagreement": 0,
    "facility_name": "Sokoto North Women and Children Welfare Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Secondary",
    "facility_level_option": "Unknown",
    "latitude": 13.06855255,
    "longitude": 5.24787129,
    "geocoordinates_source": "NHFR_2024",
    "last_updated": "2024-11-11"
  },
  {
    "OBJECTID": 46747,
    "globalid": "357c7179-bc68-40c0-b902-c59d5bcebf95",
    "nhfr_uid": 34058848,
    "nhfr_facility_code": "33/16/1/1/1/0012",
    "country": "Nigeria",
    "iso": "NGA",
    "state": "Sokoto",
    "lga": "Sokoto North",
    "lga_name_disagreement": 0,
    "ward": "Sarkin Musulmi A",
    "ward_name_disagreement": 0,
    "facility_name": "Sultan Palace Health Clinic",
    "facility_name_source": "NHFR_2024",
    "ownership": "Public",
    "ownership_type": "State Government",
    "facility_level": "Primary",
    "facility_level_option": "Health Post",
    "latitude": 13.06738757,
    "longitude": 5.24825041,
    "geocoordinates_source": "NHFR_2024",
    "last_updated": "2024-11-11"
  }
]

